language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-user:v8 quochuy3456/udagram-api-user:v8
  - docker tag udagram-api-feed:v8 quochuy3456/udagram-api-feed:v8
  - docker tag udagram-frontend:v8 quochuy3456/udagram-frontend:v8
  - docker tag reverseproxy:v8 quochuy3456/reverseproxy:v8

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quochuy3456/udagram-api-user:v8
  - docker push quochuy3456/udagram-api-feed:v8
  - docker push quochuy3456/udagram-frontend:v8
  - docker push quochuy3456/reverseproxy:v8
