version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v11

  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v11

  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v11

  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v11
