version: "3"
services:
  reverseproxy:
      image: reverseproxy:v8
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed

  backend-user:
    image: udagram-api-user:v8
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: "default"
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  backend-feed:
    image: udagram-api-feed:v8
    volumes:
      - "C:/Users/ADMIN/.aws:/root/.aws"
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: "default"
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  frontend:
    image: udagram-frontend:v8
    ports:
      - "8100:80"
